### ISSUE TITLE
Feature Discord Bot

### ISSUE THREAD

**Issue by elwoujdi** [ibrahim-kabir/discord-skinwalker-bot#1]
# Context
This feature will incorporate a Discord Bot that will call different services and responds to user commands.

# Tasks
- [x] Listen for user join and leave events in voice channels.
- [x] Responds to commands
- [x] Call the RecordingService 

# Acceptance criteria
* Randomly join the most active voice channel.
* Select the first voice channel channel with more than 2 users.
* Leave the voice channel after repeating a sentence.
* Offer a command to configure the appearance frequency.
* Offer a command to kick the bot of the voice channel
