### ISSUE TITLE
Feature Recording Service

### ISSUE THREAD

**Issue by elwoujdi** [ibrahim-kabir/discord-skinwalker-bot#3]
# Context
This discord bot has for goal to record users in a voice chat populated by more than two users and to save each sentences said in a single mp3 file. This service will be necessary to repeat users sentences. 

# Tasks
- [x] Create a discord bot that joins the channel.
- [ ] Initialize an audio recording when 2 or more users are in a voice channel.
- [ ] Save acceptable phrases to the database
- [ ] Schedule a mechanism to delete recordings older than one hour.

# Acceptance Criteria
* The bot joins the call to start recording.
* Continuously record conversations in selected voice channels.
* Doesn't record everyone in a same file. It needs to record individually so we can only hear one person at a time.
* Detect individual sentences based on silence and volume.
* Do not repeat sentences longer than 10 seconds.
* Sentence starts when the user talks for more than 2 secondes and ends when user stops talking for more than 1 second
* Slice mp3 files by sentences
* Repeat phrases randomly within the last 60 minutes.
* Prioritize phrases with high volume.
* Do not repeat phrases that have already been played.
